name: NEW_PRICE_ALERT

on:
  schedule:
    - cron: "0 9 * * 1"  # runs daily at 9am UTC
  push:
    branches:
      - 'main'
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install serpapi

      - name: Run script
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: python main2.py
        
      - name: Send email
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: python send_email.py
